### ISSUE TITLE
Rumskib blocks `minor` missions from offering

### ISSUE THREAD

**Issue by Yamakuzure** [TheGiraffe3/rumskib#1]
I have no idea how this is even possible, but whenever I have rumskib enabled I can not proceed with the Remnants.

(Note: It might be that other missions are also affected, but I only know about these two for certain.)

Symptoms:

1. No matter whether I have 1 or 12 (my maximum so far) broken jump drives in my cargo, the broken jump drive line of missions does not trigger. After deactivating rumskib and restarting the game, departing and landing triggers the broken jump drive mission.
2. Although all prerequisites are fulfilled, I can visit the Spaceport on Caelian as often as I want, the mission to learn sign language does not trigger. After deactivating rumskib and restarting the game, the first visit of the Spaceport triggered the learn sign mission.

Unfortunately I do not have had a save going back far enough to showcase this.
As a "workaround" I _pimped_ the Lampyrid from an "Lampyrid_Start.v1.6" early started game to get as fast as possible to the Remnant and to get a broken jump drive quickly. The save is attached.
If you depart and land with Rumskib activated, nothing happens. If Rumskib is deactivated, the first Broken jump Drive mission triggers.
[William Riker~Rumskib-Remnant-Bug-Demo-1.txt](https://github.com/user-attachments/files/18266547/William.Riker.Rumskib-Remnant-Bug-Demo-1.txt)

**Comment by TheGiraffe3** [comment]
I believe this is caused by the `minor` and `repeat` tags in the Blended ship compatibility mission.
The fix for it will require the latest continuous version of Endless Sky so that the `non-blocking` tag exists.
Would you be willing to download the latest release of Endless Sky and the latest release of this plugin to re-test?
With d32f9848cee174dcbbe4709d01e6c2019ec07234 it seems to work.

**Comment by Yamakuzure** [comment]
I have managed to get a live build running and pulled your latest commits.

After loading my attached save file, I had to depart and land twice, but the missing mission triggered after the second landing.

You have successfully fixed that bug; thank you very much!

**Comment by TheGiraffe3** [comment]
Glad it worked!
